### PR TITLE
Faster unaligned read_bytes

### LINKED ISSUE #30: Faster way to read unaligned bytes
Currently "unaligned" bytes are read with "read and refill", but I think we could do quite a bit better.

The idea is to take the buffer as is and bitshift the all bytes in one loop with SIMD.

The below produces nice auto-vectorized code that is >10x faster on bigger reads.

For example here we are "4 bits into a byte":
```Rust
pub fn read_n_bytes(&mut self, n: usize, input: &[u8], out: &mut [u8]) {
    let left_mask = 0b00001111;
    let right_mask = 0b11110000;
    for i in 0..n {
        let left_part = input[i] & left_mask;
        let right_part = input[i + 1] & right_mask;
        out[i] = left_part | right_part;
    }
}
```
I gave it a shot myself but couldn't quite get the state correct after this operation.

### PR DESCRIPTION
**Pull request by nickbabcock**
Benchmarks:
 - At 5 byte reads, `read_bytes` is 35-40% faster for both byte aligned and unaligned reads
 - At 960 byte reads, unaligned reads improved by 22x
 - Aligned read performance at other byte sizes remained unchanged.

Closes #30

### CODE REVIEW

**Comment by LaihoE** [comment]
Yeah this is exactly what I was after. Btw I just ran the test with the old version and it doesn't pass the test. Could you maybe re-check that the test passes with the old version?

**Comment by LaihoE** [comment]
https://rust.godbolt.org/z/7W45jzE1h

I think this is the hot loop:
```
.LBB0_18:
        movdqu  xmm5, xmmword ptr [rdx + rcx]
        movdqu  xmm6, xmmword ptr [rdx + rcx + 1]
        psrlw   xmm5, xmm0
        pand    xmm5, xmm3
        pand    xmm5, xmm1
        psllw   xmm6, xmm2
        pand    xmm6, xmm4
        paddb   xmm6, xmm5
        movdqu  xmmword ptr [r8 + rcx], xmm6
        add     rcx, 16
        cmp     r10, rcx
        jne     .LBB0_18
```
seems fine

**Comment by nickbabcock** [comment]
Great catch on the test case. I've fixed it, I've also run benchmarks. Great improvements across the board (for aligned and unaligned, and for all read sizes), culminating in a 22x throughput increase for unaligned byte reads at 960 bytes.

**Comment by LaihoE** [comment]
Amazing job, tried it and it worked perfect. I tested it in my workflow on >10 million read_bytes calls and it works exactly the same as old version but just much faster 👍

**Comment by nickbabcock** [comment]
Great to hear, and thank you for the verification! I also see everything passing on my own corpus of data 👍 

Let me merge this and issue a 0.6.2 release

**Pull request merged**
